language: csharp
solution: Calendary.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore Calendary.sln
script:
  - xbuild /p:Configuration=Release Calendary.sln
  - nunit-console src.test/bin/Release/src.test.dll
